### ISSUE TITLE
DYLD_LIBRARY_PATH

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/libgd-feedstock#5]
I'm a bit confused about this:

```
if [[ failed -eq 1 ]]; then
    grep -rl "DYLD_LIBRARY_PATH=" tests | xargs sed -i.bak "s~DYLD_LIBRARY_PATH=.*~DYLD_LIBRARY_PATH=$PREFIX/lib~g"
make check
```

isn't it important that it work in a conda environment without having to mess with DYLD_LIBRARY_PATH?

or is the build environment different than the installed environment in this regard?

**Comment by croth1** [comment]
This is just a dirty hack to get the test suite running - it does not affect the installation itself. The patched files are just run in the build environment, but never installed.

**Comment by ChrisBarker-NOAA** [comment]
got it -- thanks!
