### ISSUE TITLE
cmake?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/libgd-feedstock#6]
Have you tried cmake for this? It looks like they are shipping the configure script now, so that's good, but cmake may be a better option for Windows. 

of course, we can use it only on Windows, but I thought I'd ask if it's been tried at all.

**Comment by croth1** [comment]
yes I tried the cmake build at some point, but I had troubles because it did not install some files. See my issue here for details: https://github.com/conda/conda-recipes/issues/625.

**Comment by ChrisBarker-NOAA** [comment]
thanks -- I found cmake painful as well....

We'll have to see how things go on Windows
