### ISSUE TITLE
Add a Windows build

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/libgd-feedstock#9]
We really need this on Windows.

We have a really hacky Windows recipe here:

https://github.com/NOAA-ORR-ERD/orr-conda-recipes/tree/master/libgd

only known to work with py2.7 -- i.e. VS2008

I"m not sure how to make different versions with different compilers -- features?

but this could be a starting place.

**Comment by croth1** [comment]
Sorry, I don't have a windows machine, I cannot really help you here 👎

**Comment by ChrisBarker-NOAA** [comment]
This had been done for a while :-)
